<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class AuditLogsController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $session = $this->request->getSession();

        // Namespaced session key (important for reuse)
        $sessionKey = 'AuditLogs.index.filters';

        // Reset filters
        if ($this->request->getQuery('reset')) {
            $session->delete($sessionKey);
            return $this->redirect(['action' => 'index']);
        }

        // Create a filter entity (DTO-style)
        $filters = $this->AuditLogs->newEmptyEntity();

        // Read incoming data (POST preferred, fallback to session)
        if ($this->request->is(['post', 'put', 'patch'])) {
            $data = $this->request->getData();
            $session->write($sessionKey, $data);
        } else {
            $data = $session->read($sessionKey) ?? [];
        }

        // Apply filters to entity
        if (!empty($data)) {
            $filters = $this->AuditLogs->patchEntity($filters, $data);
        }

        // Build query
        $query = $this->AuditLogs->find()
            ->orderDesc('AuditLogs.created')
            ->limit(20);

        // Example filter usage (expand later)
        if (!empty($filters->name)) {
            $query->where([
                'AuditLogs.name LIKE' => '%' . $filters->name . '%'
            ]);
        }

        // Pass to view
        $this->set([
            'AuditLogs' => $filters,
            'rows' => $query->all(),
        ]);



        // IGNORE
        $this->set('AuditLogs_title', 'Upload A File');
        $this->set('AuditLogs_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('AuditLogs_renderFiles', [
            'Template' => APP . '../templates/Staff/AuditLogs/index.php'
        ]);
        $this->set('AuditLogs_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\AuditLogsController::class, 'index')
        ]);
        // IGNORE-END


    }//index



    public function duplicate($id) {
        if (!$id) {
            $this->Flash->error('Specify ID');
            return $this->redirect($this->referer());
        } else {
            // Fetch the existing entity
            $entity = $this->AuditLogs->get($id);

            // Convert the entity to an array, reset the id and other fields that need to be unique
            $data = $entity->toArray();
            unset($data['id']); // Remove the ID to let CakePHP know it's a new entity

            // Create a new entity instance with the duplicated data
            $newEntity = $this->AuditLogs->newEntity($data);

            if ($this->AuditLogs->save($newEntity)) {
                $this->Flash->success('Duplicated ' . $newEntity->name);
                return $this->redirect(['action' => 'edit', $newEntity->id]);
            } else {
                $this->Flash->error('Error, cannot duplicate');
                return $this->redirect($this->referer());
            }
        }
    }




    public function view($id)
    {
        try {
            $entity = $this->AuditLogs->get($id, [
                // 'contain' => ['RelatedTable'], // future-ready
            ]);
        } catch (\Cake\Datasource\Exception\RecordNotFoundException $e) {
            $this->Flash->error(__('Record not found.'));
            return $this->redirect(['action' => 'index']);
        }

        $this->set([
            'entity' => $entity,
            'pageTitle' => 'View Code Block',
            'pageSubTitle' => 'Read-only details',
        ]);

        // IGNORE
        $this->set('AuditLogs_title', 'View');
        $this->set('AuditLogs_subTitle', 'View one record with standard layout');
        $this->set('AuditLogs_renderFiles', [
            'Template' => APP . '../templates/Staff/AuditLogs/view.php'
        ]);
        $this->set('AuditLogs_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\AuditLogsController::class, 'index')
        ]);
        // IGNORE-END
    }












}
