<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class CodeBlocksController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        // Intro / landing page for CodeBlocks

        //From Latha here
        $query = $this->CodeBlocks->find()
            ->order([
                'CodeBlocks.created' => 'DESC',
            ])
            ->limit(20);

        $records = $query->all(); // returns ResultSetInterface

        $this->set(compact('records'));
    }


    public function create()
    {
        $entity = $this->CodeBlocks->newEmptyEntity();

        if ($this->request->is('post')) {
            $entity = $this->CodeBlocks->patchEntity(
                $entity,
                $this->request->getData()
            );

            if ($this->CodeBlocks->save($entity)) {
                $this->Flash->success(__('The record has been created successfully.'));

                return $this->redirect([
                    'action' => 'index',
                ]);
            }

            $this->Flash->error(__('The record could not be created. Please try again.'));
        }

        $this->set(compact('entity'));
    }

    public function view($id = null)
    {
        try {
            $entity = $this->CodeBlocks->get($id);
        } catch (\Cake\Datasource\Exception\RecordNotFoundException $e) {
            $this->Flash->error(__('Record not found.'));
            return $this->redirect(['action' => 'index']);
        }

        $this->set(compact('entity'));
    }




    function duplicate($id)
    {
        if (!$id) {
            $this->Flash->error('Specify ID');
            return $this->redirect($this->referer());
        } else {
            // Fetch the existing template clause with related template contracts
            $entity = $this->CodeBlocks->get($id);

            // Convert the entity to an array and reset the id
            $data = $entity->toArray();
            unset($data['id']);
            unset($data['created']);
            unset($data['modified']);

            // Create a new entity instance with the duplicated data
            $newEntity = $this->CodeBlocks->newEntity($data);

            if ($this->CodeBlocks->save($newEntity)) {
                $this->Flash->success('Template clause duplicated successfully');
                return $this->redirect(['action' => 'edit', $newEntity->id]);
            } else {
                $this->Flash->error('Error duplicating template clause');
                return $this->redirect($this->referer());
            }
        }
    }







}
