<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class CodeBlocksController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $session = $this->request->getSession();

        // Namespaced session key (important for reuse)
        $sessionKey = 'CodeBlocks.index.filters';

        // Reset filters
        if ($this->request->getQuery('reset')) {
            $session->delete($sessionKey);
            return $this->redirect(['action' => 'index']);
        }

        // Create a filter entity (DTO-style)
        $filters = $this->CodeBlocks->newEmptyEntity();

        // Read incoming data (POST preferred, fallback to session)
        if ($this->request->is(['post', 'put', 'patch'])) {
            $data = $this->request->getData();
            $session->write($sessionKey, $data);
        } else {
            $data = $session->read($sessionKey) ?? [];
        }

        // Apply filters to entity
        if (!empty($data)) {
            $filters = $this->CodeBlocks->patchEntity($filters, $data);
        }

        // Build query
        $query = $this->CodeBlocks->find()
            ->orderDesc('CodeBlocks.created')
            ->limit(20);

        // Example filter usage (expand later)
        if (!empty($filters->name)) {
            $query->where([
                'CodeBlocks.name LIKE' => '%' . $filters->name . '%'
            ]);
        }

        // Pass to view
        $this->set([
            'codeBlocks' => $filters,
            'rows' => $query->all(),
        ]);



        // IGNORE
        $this->set('codeBlocks_title', 'Upload A File');
        $this->set('codeBlocks_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/Staff/CodeBlocks/index.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\CodeBlocksController::class, 'index')
        ]);
        // IGNORE-END


    }//index



    public function duplicate($id) {
        if (!$id) {
            $this->Flash->error('Specify ID');
            return $this->redirect($this->referer());
        } else {
            // Fetch the existing entity
            $entity = $this->CodeBlocks->get($id);

            // Convert the entity to an array, reset the id and other fields that need to be unique
            $data = $entity->toArray();
            unset($data['id']); // Remove the ID to let CakePHP know it's a new entity

            // Create a new entity instance with the duplicated data
            $newEntity = $this->CodeBlocks->newEntity($data);

            if ($this->CodeBlocks->save($newEntity)) {
                $this->Flash->success('Duplicated ' . $newEntity->name);
                return $this->redirect(['action' => 'edit', $newEntity->id]);
            } else {
                $this->Flash->error('Error, cannot duplicate');
                return $this->redirect($this->referer());
            }
        }
    }


    public function create()
    {
        $entity = $this->CodeBlocks->newEmptyEntity();

        if ($this->request->is('post')) {
            $entity = $this->CodeBlocks->patchEntity(
                $entity,
                $this->request->getData()
            );

            if ($this->CodeBlocks->save($entity)) {
                $this->Flash->success(__('The record has been created successfully.'));

                return $this->redirect(['action' => 'index']);
            }

            $this->Flash->error(__('The record could not be created. Please try again.'));
        } else {
            $cameFrom = $this->request->referer(true);
        }

        $this->set([
            'entity'   => $entity,
            'cameFrom' => $cameFrom,
            'isCreate' => true,
            'pageTitle' => 'Create Code Block',
            'pageSubTitle' => 'Define the basic details',
        ]);

        // Reuse Manager template
        $this->viewBuilder()->setTemplate('/Manager/CodeBlocks/edit');





        // IGNORE
        $this->set('codeBlocks_title', 'Create a new Record');
        $this->set('codeBlocks_subTitle', 'Create new and share with the Manager EDIT template');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/Manager/CodeBlocks/edit.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\CodeBlocksController::class, 'create')
        ]);
        // IGNORE-END


    }


    public function view($id)
    {
        try {
            $entity = $this->CodeBlocks->get($id, [
                // 'contain' => ['RelatedTable'], // future-ready
            ]);
        } catch (\Cake\Datasource\Exception\RecordNotFoundException $e) {
            $this->Flash->error(__('Record not found.'));
            return $this->redirect(['action' => 'index']);
        }

        $this->set([
            'entity' => $entity,
            'pageTitle' => 'View Code Block',
            'pageSubTitle' => 'Read-only details',
        ]);




        //$this->Flash->success('success88888888');
        //$this->Flash->error('erroroooooooooo');
        $this->Flash->info('info goes here');


        // IGNORE
        $this->set('codeBlocks_title', 'View');
        $this->set('codeBlocks_subTitle', 'View one record with standard layout');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/Staff/CodeBlocks/view.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\CodeBlocksController::class, 'index')
        ]);
        // IGNORE-END
    }












}
