<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;
use Cake\View\View;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class EmailQueuesController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    function emailAddToQueue(){

        $order_id = rand(1,100);

        $user_id = 99;


        $this->set('order_id', $order_id);
        $this->set('codeBlocks_title', 'Email Add to Queue');



        $view = new View();
        $view->set([
            'user_id' => $user_id,
            'order_id' => $order_id
        ]);

        $message_html = $html = $view->element('emails/order_confirmation');
        $message_text  = strip_tags($message_html);
        $entity = $this->EmailQueues->newEmptyEntity();
        $entity->user_id = $user_id;
        $entity->order_id = $order_id;
        $entity->message_html = $message_html;
        $entity->message_text = $message_text;
        $entity->letter = 'order_confirmation';
        $entity->email_to = 'test@test.com';
        $entity->email_from = 'support@undologic.com';
        $entity->lang = 'en';
        $entity->sent = 0;
        $entity->json_data = json_encode($entity);

        if($this->EmailQueues->save($entity)){
            $response = ['STATUS'=>200, 'MESSAGE'=>'Email  added to Queue'];

        }else{
            $response = ['STATUS'=>400, 'MESSAGE'=>'Email  FAILED to add to Queue'];
        }
        $entity_saved = $entity;
        $entity_saved->response = json_encode($response);

        $this->EmailQueues->save($entity_saved);




        $this->set('codeBlocks_subTitle', 'Procedure for Emails Add to Queue');
//        $this->set('codeBlocks_renderFiles', [
//            'Template' => APP . '../templates/staff/EmailQueues/email_add_to_queue.php'
//        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\EmailQueuesController::class, 'addToQueue'),
//        ]);

        $queues = $this->EmailQueues->find()->where(['EmailQueues.sent' => 0]);
        $this->set(compact('queues'));
    }


    function addToQueue(){
        $user_id = 1;
        $order_id = 99;



        $this->set(compact('user_id', 'order_id'));


    }









}// end
