<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */

namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Mailer\Mailer;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;
use Cake\View\View;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class EmailQueuesController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        $session = $this->request->getSession();

        // Namespaced session key (important for reuse)
        $sessionKey = 'Emailers.index.filters';

        // Reset filters
        if ($this->request->getQuery('reset')) {
            $session->delete($sessionKey);
            return $this->redirect(['action' => 'index']);
        }

        // Create a filter entity (DTO-style)
        $filters = $this->EmailQueues->newEmptyEntity();

        // Read incoming data (POST preferred, fallback to session)
        if ($this->request->is(['post', 'put', 'patch'])) {
            $data = $this->request->getData();
            $session->write($sessionKey, $data);
        } else {
            $data = $session->read($sessionKey) ?? [];
        }

        // Apply filters to entity
        if (!empty($data)) {
            $filters = $this->EmailQueues->patchEntity($filters, $data);
        }

        // Build query
        $query = $this->EmailQueues->find()
            ->orderDesc('EmailQueues.created')
            ->limit(20);

        // Example filter usage (expand later)
        if (!empty($filters->name)) {
            $query->where([
                'EmailQueues.name LIKE' => '%' . $filters->name . '%'
            ]);
        }

        // Pass to view
        $this->set([
            'EmailQueues' => $filters,
            'rows' => $query->all(),
        ]);


    }

    public function view($id)
    {
        try {
            $entity = $this->EmailQueues->get($id, [
                // 'contain' => ['RelatedTable'], // future-ready
            ]);
        } catch (\Cake\Datasource\Exception\RecordNotFoundException $e) {
            $this->Flash->error(__('Record not found.'));
            return $this->redirect(['action' => 'index']);
        }

        $this->set([
            'entity' => $entity,
            'pageTitle' => 'View Code Block',
            'pageSubTitle' => 'Read-only details',
        ]);

    }

    function emailAddToQueue()
    {

        $order_id = rand(1, 100);

        $user_id = 99;


        $this->set('order_id', $order_id);
        $this->set('codeBlocks_title', 'Email Add to Queue');


        $view = new View();
        $view->set([
            'user_id' => $user_id,
            'order_id' => $order_id
        ]);

        $raw_html = $view->element('emails/order_confirmation');
        $styled_html = SetupCase::styleTables($raw_html);
        $text_html = strip_tags($raw_html);

        $message_html = $styled_html;
        $message_text = $text_html;
        $entity = $this->EmailQueues->newEmptyEntity();
        $entity->user_id = $user_id;
        $entity->order_id = $order_id;
        $entity->message_subject = 'Email Subject';
        $entity->message_html = $message_html;
        $entity->message_text = $message_text;
        $entity->letter = 'order_confirmation';
        $entity->email_to = 'setupcase@undoweb.com';
        $entity->email_from = 'support@undoweb.com';
        $entity->lang = 'en';
        $entity->sent = 0;
        $entity->json_data = json_encode($entity);

        if ($this->EmailQueues->save($entity)) {
            $response = ['STATUS' => 200, 'MESSAGE' => 'Email  added to Queue'];

        } else {
            $response = ['STATUS' => 400, 'MESSAGE' => 'Email  FAILED to add to Queue'];
        }
        $entity_saved = $entity;
        $entity_saved->response = json_encode($response);

        $this->EmailQueues->save($entity_saved);


        $this->set('codeBlocks_subTitle', 'Procedure for Emails Add to Queue');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/staff/EmailQueues/email_add_to_queue.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\EmailQueuesController::class, 'addToQueue'),
        ]);

        $queues = $this->EmailQueues->find()->where(['EmailQueues.sent' => 0]);
        $this->set(compact('queues'));

        $this->Flash->success('Added to Queue');
        $this->redirect($this->referer());
    }

    function addToQueue()
    {
        $user_id = 1;
        $order_id = 99;


        $this->set(compact('user_id', 'order_id'));


    }

    function send($id)
    {

        try {
            $entity = $this->EmailQueues->get($id, [
                // 'contain' => ['RelatedTable'], // future-ready
            ]);
        } catch (\Cake\Datasource\Exception\RecordNotFoundException $e) {
            $this->Flash->error(__('Record not found.'));
            return $this->redirect(['action' => 'index']);
        }

        if ($entity->sent) {
            $this->Flash->error('Email Already Sent');
            return $this->redirect($this->referer());
        } else {

            $vars = [
                'id' => $id,
                'message_html' => $entity['message_html'],
                'message_text' => $entity['message_text'],
            ];
            $didSend = SetupCase::sendEmail(
                $entity->email_to,
                'email_queues',
                $entity->email_from,
                $entity->message_subject,
                $vars,
                $cc = false,
                $attachments = []
            );

            if ($didSend) {

                $entity->sent = 1;
                $this->EmailQueues->save($entity);
                die('SUCCESS: Email Sent !');

            } else {
                die('ERROR: Email NOT Sent');
            }

        }

    }


}// end
