<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Staff;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class UsersController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    function switchToUser(){


        $this->set('codeBlocks_title', 'Swtich into user (switch user)');
        $this->set('codeBlocks_subTitle', 'Allows to switch into that user
- Great for Admin / Manage allowing them to view the same screen a customer is viewing
- Allows to diagnose without creating complex logins with different types');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/Staff/Users/switch_to_user.php'
        ]);
         $this->set('codeBlocks_renderVar', [
             'Controller Action' => SetupCase::extractFunction(\App\Controller\Staff\UsersController::class, 'switchUser'),
         ]);

    }

    function switchUser(){
        $given_user_id = 9999;
        $user = $this->Users->get($given_user_id);
        // dd($user);
        if (!empty($user)) {
            $res = $this->Authentication->setIdentity($user);
            $this->Flash->success("You have been logged in");
        } else {
            $this->Flash->error("User not found");
        }
    }

    function resetPassword(){
        $this->set('codeBlocks_title', 'Reset Password');
        $this->set('codeBlocks_subTitle', 'Allows user to reset password');
    }





}
