<?php
declare(strict_types=1);

namespace App\View\Helper;

use Cake\View\Helper;
use Cake\View\View;

/**
 * Auth helper
 */
class AuthHelper extends Helper
{
    /**
     * Default configuration.
     *
     * @var array<string, mixed>
     */
    protected $_defaultConfig = [];

    function initialize(array $config): void
    {
        parent::initialize($config); // TODO: Change the autogenerated stub

//        pr ('AuthHelper - init');
//        dd ($this->request);
    }

    function isLoggedIn() {


        //dd('hello');
        return 'Auth helper works';

    }

}


