<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller\Manager;

use App\Controller\AppController;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class LocationsController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }


    public function edit($id = false)
    {

        $entity = $this->Locations->get($id, ['contain'=>['Users']]);

        if ($this->request->is(['post', 'put', 'patch'])) {
            $data = $this->request->getData();
            $cameFrom = $data['cameFrom'] ?? null;

            unset($data['cameFrom']); // critical

            $entity = $this->Locations->patchEntity($entity, $data);

            if ($this->Locations->save($entity)) {
                //$this->Flash->success(__('The record has been updated successfully.'));

                $this->Flash->success('Saved successfully.');

                return $this->redirect(
                    $this->safeRedirect($cameFrom, ['action' => 'index'])
                );
            }

            $this->Flash->error(__('The record could not be updated. Please try again.'));
        } else {
            $cameFrom = $this->request->referer(true);
        }

        $this->set([
            'entity' => $entity,
            'cameFrom' => $cameFrom,
            'isCreate' => false,
            'pageTitle' => 'Edit Locations',
            'pageSubTitle' => 'Update details and associated classes (Locations has BelongsToMany Users)',
            'users' => $this->Locations->Users->find('list')
        ]);


        // IGNORE
        $this->set('Locations_title', 'Edit a file');
        $this->set('Locations_subTitle', '');
        $this->set('Locations_renderFiles', [
            'Template' => APP . '../templates/Manager/Locations/edit.php'
        ]);
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/Manager/Locations/edit.php'
        ]);
        $this->set('Locations_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\Manager\LocationsController::class, 'edit')
        ]);
        // IGNORE-END

    }













}
