<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class CodeBlocksController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function dashboard() {

    }

    public function index() {
        //Intro page
    }

    public function home() {

    }



    public function responsiveTable() {

        $this->set('codeBlocks_title', 'Responsive Table');
        $this->set('codeBlocks_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/CodeBlocks/responsive_table.php'
        ]);

    }



    public function uploadFile() {

        if (!empty($this->request->getData())) {
            $attachment = $this->request->getData('file');
            $filename = $attachment->getClientFilename();
            $typeOfUpload = $attachment->getClientMediaType();
            $size = $attachment->getSize();
            $uploadedFile = $attachment->getStream()->getMetadata('uri');
            $error = $attachment->getError();

            $csvFile = $uploadedFile;

            $filename = APP.'Files'.DS.'uploadProducts_'.date('YmdHis').'.csv';

            file_put_contents($filename,
                file_get_contents($csvFile)
            );

        }

        // IGNORE
        $this->set('codeBlocks_title', 'Upload A File');
        $this->set('codeBlocks_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/upload_file.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
        ]);
        // IGNORE-END


    }



    function readMore() {


        // IGNORE
        $this->set('codeBlocks_title', 'Read More Expanded Text');
        $this->set('codeBlocks_subTitle', 'Long text is faded away - Click link to expanded and show all faded text');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/read_more.php'
        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
//        ]);
        // IGNORE-END
    }



    function sticky() {


        // IGNORE
        $this->set('codeBlocks_title', 'Sticky');
        $this->set('codeBlocks_subTitle', 'Keep a div floating as the window scrolls down');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/sticky.php'
        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
//        ]);
        // IGNORE-END
    }



}
