<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\EventInterface;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        /*
         * Enable the following component for recommended CakePHP form protection settings.
         * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
         */
        //$this->loadComponent('FormProtection');
    }

    function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

        $current_language = $this->setupLanguage();

    }

    function setupAuth() {
        //if they are logged in (does a session exist called $session->read('User')
            //if they do have this
                //$this->>set('isLoggedIn', true);
                //check the user_type_id

        $acl = [
            'Admin' => 111,
            'User' => 10,
            'Staff' => 50
        ];

        //check our current prefix
            //$this->isAllowedPrefix($this->getPrefix())
                //we are allowed
            //else - NOT ALLOWED THE PREFIX
                //show message you are not allowed the current  prefix and redirect to referer (so they will go back to the screen


        //if isset(prefix
            //can we loop through prefixes ?
                //check each Name of the prefix against our list (keep our list in this function for now)
                if (isset($acl[ $prefix ])) {
                    if ($user['User']['user_type_id'] == $acl[ $prefix ]) {
                        //we
                    }
                }
    }

    private function isAllowedPrefix($prefix) {

    }

    function setupLanguage()
    {
        $url_language = $this->request->getParam('language');
        if ($url_language != null && in_array($url_language, ['en_US', 'fr_CA'])) {
            //if there is a language in the address bar
            $current_language = $url_language;
            $this->session()->write(['current_language' => $url_language]);
            $this->language = $current_language;
        }elseif(!empty($this->session()->read('current_language'))) {
            // if we have a language session
            $current_language = $this->session()->read('current_language');
            $this->session()->write(['current_language' => $current_language]);
            $this->language = $current_language;
        }elseif(isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
            // we use what the browser language they are viewing
            $current_language = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 5);
            $current_language = str_replace('-', '_', $current_language);
            $this->session()->write(['current_language' => $current_language]);
            $this->language = $current_language;
        }else{
            // default language
            $current_language = 'en_US';
            $this->language = $current_language;
            $this->session()->write(['current_language' => $current_language]);
        }

        //Make sure we always have a language in the address bar
        $attributes = $this->request->getAttributes();
        if (!isset($attributes['params']['language'])) {
            $redirectArray = array();
            $redirectArray['language'] = $this->language;
            if (isset($attributes['params']['?'])) {
                $redirectArray['?'] = $attributes['params']['?'];
            }
            if (!empty($attributes['params']['pass'])) {
                $redirectArray = $redirectArray +$attributes['params']['pass'];
            }

            //if we are trying to access / let's auto assume /Pages/index
//            if (!isset($redirectArray['controller'])) {
//                $redirectArray['controller'] = 'Pages';
//            }
//            if (!isset($redirectArray['action'])) {
//                $redirectArray['action'] = 'index';
//            }
//            $this->log($redirectArray, 'debug');
            //$this->writeToLog('debug','hello');
            //pr ('will redirect to');
            //pr ($redirectArray);
            //exit;

            $this->redirect($redirectArray);
        }

        //in our view we only care about a basic language (eg en / fr) not the extended version of a language
        if (substr($current_language, 0, 2) === 'fr') {
            $this->set('baseLang','fr');
        } else {
            $this->set('baseLang', 'en');
        }

        $this->set(compact('current_language'));

        return $current_language;
    }// end of setupLanguage

    private function session(){
        $session = $this->getRequest()->getSession();
        return $session;
    }

    public function writeToLog($filename, $message, $newLine = false) {
        if ($newLine) {
            $message = "\n".date('Ymd-His').' > '.$message;
        } else {
            $message = ' > '.$message;
        }
        pr (APP);exit;


        //file_put_contents(APP.'tmp/logs/'.$filename.'.log', $message, FILE_APPEND);
    }

}
