<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\EventInterface;
use Cake\Routing\Router;
use Cake\I18n\I18n;
use Cake\I18n\Time;
use Cake\I18n\Number;



/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->viewBuilder()->setLayout('a');
        $this->set('webroot', Router::url('/'));
        $this->set('base', Router::url('/modules'));
        $this->Authentication->addUnauthenticatedActions(['login', 'add']);


        /*

        $blobImage = file_get_contents(APP.'webroot'.DS.'img'.DS.'TESTimage.jpg');
        $blobImage = file_get_contents('img'.DS.'TESTimage.jpg');
        $mime = 'image/jpg';
        $key_name = 'TESTING';
        $imageLink = 'link';
        $object_storage_id = ClassRegistry::init('Storage','Model')->put($key_name, $blobImage, $mime, $imageLink);
        //after success a new row will appearin tthe storage database.files
        //then go look at phpmyadmin and you should be able to click 'blob' to dowload (change the extension to .jpg' and open the picture

        */
        // set language
        $current_locale = I18n::getLocale();
        $this->set(compact('current_locale'));
       // $this->setLocale();



    }

    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Authentication.Authentication');


        /*
         * Enable the following component for recommended CakePHP form protection settings.
         * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
         */
        //$this->loadComponent('FormProtection');
    }

    function setLocale(){
        $locale = I18n::getLocale();
        if($locale === 'en_US'){
            $current_locale = 'fr_CA';
            $current_language = strtoupper(explode('_', $current_locale)[0]);
           // pr($current_language); exit;
            $this->set(compact('current_locale', 'current_language'));
        }
      //  $this->set(compact('current_locale'));
        //I18n::setLocale('fr');
        // pr( I18n::getDefaultLocale());
        //pr( I18n::getLocale()); exit;
        //pr( I18n::getDefaultLocale()); exit;
    }

}
