<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Controller\Controller;
use Cake\Event\EventInterface;
use Cake\Routing\Router;
use Cake\I18n\I18n;
use Cake\I18n\Time;
use Cake\I18n\Number;
use Cake\Http\Session\DatabaseSession;




/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function beforeFilter(EventInterface $event)
    {


        //pr($this->request->getAttributes()['params']); exit;
      //  pr($this->request->getParam('controller'));
       // pr($this->request->getParam('action'));
       // exit;
        parent::beforeFilter($event); // TODO: Change the autogenerated stub



        // language
        $this->setupLanguage();

        $this->viewBuilder()->setLayout('a');
        $this->set('webroot', Router::url('/'));
        $this->set('base', Router::url('/modules'));
        $this->Authentication->addUnauthenticatedActions(['login', 'add']);

        $params = $this->request->getAttributes()['params'];
        //pr($this->request->getAttributes());
        //pr($params);
        //exit;
        $controller = $params['controller'];
        $action = $params['action'];
        if(!isset($params['language'])){
            $params['language'] = $this->getCurrentLanguage();
        }
       // $this->request->se
       // pr($this->request->getAttributes()['params']); exit;
        //pr($this->getCurrentLanguage()); exit;


    }// end of beforeFilter


    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');
        $this->loadComponent('Authentication.Authentication');

       // pr ( $this->request->getAttribute('params'));
        //exit;


    }// end of initialize

    var $language;
    function setupLanguage()
    {

       $url_language = $this->request->getParam('language');
        if ($url_language != null && in_array($url_language, ['en_US', 'fr_CA'])) {
            $current_language = $url_language;
            //add to session
            $this->session()->write(['current_language' => $url_language]);
            $this->language = $current_language;


        }elseif(!empty($this->session()->read('current_language'))) { // session

            $current_language = $this->session()->read('current_language');
            $this->session()->write(['current_language' => $current_language]);
            $this->language = $current_language;
        }elseif(isset($_SERVER['HTTP_ACCEPT_LANGUAGE'])) {
            $current_language = substr($_SERVER['HTTP_ACCEPT_LANGUAGE'], 0, 5);
            $this->session()->write(['current_language' => $current_language]);
            $this->language = $current_language;
        }else{// default manual string
            $current_language = 'en_US';
            $this->language = $current_language;
            $this->session()->write(['current_language' => $current_language]);
            }


        $this->set(compact('current_language'));


    }// end of setupLanguage

    private function session(){
        $session = $this->getRequest()->getSession();
        return $session;
    }

    function setCurrentLanguage($lang){
        $this->language = $lang;
        //session
        $this->session()->write(['current_language' => $lang]);
    }

    function getCurrentLanguage(){
        return $this->language;

    }

//
//    function setLocale($lang){
//        I18n::setLocale($lang);
//
//    }
//
//    function getLocale(){
//        $current_locale = I18n::getLocale();
//        return $current_locale;
//
//    }

}
