<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\View\Exception\MissingTemplateException;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class UsersController extends AppController
{
    /**
     * Displays a view
     *
     * @param string ...$path Path segments.
     * @return \Cake\Http\Response|null
     * @throws \Cake\Http\Exception\ForbiddenException When a directory traversal attempt.
     * @throws \Cake\View\Exception\MissingTemplateException When the view file could not
     *   be found and in debug mode.
     * @throws \Cake\Http\Exception\NotFoundException When the view file could not
     *   be found and not in debug mode.
     * @throws \Cake\View\Exception\MissingTemplateException In debug mode.

     */

    function beforeFilter(EventInterface $event)
    {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub

    }

    // index
    public function index(){

        $users = $this->Users->find('all');
        $users = $users->toArray();

        $this->set(compact('users'));
    }
    // view
    public function view($id = null){
        $user = $this->Users->get($id, [
            'contain' => []
        ]);
    }
    public function edit(){

    }
    public function jsonAddUser(){
        $objData=file_get_contents('php://input');
        if(empty($objData)){
            $objData = '{"name":"testName"}';
        }
        if($this->Users->jsonAddUser($objData)){
            echo true;
        }else{
            echo false;
        }
        exit;
    }

    public function add(){

            $users = $this->Users->newEmptyEntity();

            if ($this->request->is('post')) {
                $users = $this->Users->patchEntity($users, $this->request->getData());

                if ($this->Users->save($users)) {
                    $this->Flash->success(__('The User has been saved.'));

                    return $this->redirect(['action' => 'index']);
                }
                $this->Flash->error(__('The User could not be saved. Please, try again.'));
            }




    }// end of add


}// end
