<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use App\Util\SetupCase;
use Cake\Controller\Controller;
use Cake\Event\EventInterface;
use Cake\Routing\Router;

/**
 * Application Controller
 *
 * Add your application-wide methods in the class below, your controllers
 * will inherit them.
 *
 * @link https://book.cakephp.org/4/en/controllers.html#the-app-controller
 */
class AppController extends Controller
{
    /**
     * Initialization hook method.
     *
     * Use this method to add common initialization code like loading components.
     *
     * e.g. `$this->loadComponent('FormProtection');`
     *
     * @return void
     */
    public function initialize(): void
    {
        parent::initialize();

        $this->loadComponent('RequestHandler');
        $this->loadComponent('Flash');

        $this->loadComponent('Authentication.Authentication');

        /*
         * Enable the following component for recommended CakePHP form protection settings.
         * see https://book.cakephp.org/4/en/controllers/components/form-protection.html
         */
        //$this->loadComponent('FormProtection');


    }


    public function beforeFilter(EventInterface $event) {
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
        $this->setupCase();
    }
    function setupCase() {

        $setupCase = new SetupCase;
        $setupCase->requirePasswordExcept(['www.LIVESITE.com', 'LIVESITE.com'], $_SERVER, $this->request->getSession());
        $setupCase->requireSSLExcept([
            'localhost', //add other hosts which should NOT redict to SSL
        ], $this);

        //redirect older langs
//    $oldLangCheck = $this->request->getParam('language');
//    if ($oldLangCheck == 'eng') {
//        $this->redirect(['language' => 'en']);
//    } elseif ($oldLangCheck == 'fre') {
//        $this->redirect(['language' => 'fr']);
//    }

        //RBAC/Access middleware decides if they are allowed in - here we redirect if needed
        $access_granted = $this->request->getAttribute('access_granted');
        if (!$access_granted) {
            $this->Flash->error($this->request->getAttribute('access_msg'));
            $this->redirect($this->referer());
        } else {
            //We handle all RBAC from our RBAC middleware - disable the CakePHP authentication for all pages
            $this->Authentication->addUnauthenticatedActions([$this->request->getAttribute('params')['action']]);
        }

        $this->set('webroot', Router::url('/'));
    }


}
