<?php
declare(strict_types=1);

/**
 * CakePHP(tm) : Rapid Development Framework (https://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 *
 * Licensed under The MIT License
 * For full copyright and license information, please see the LICENSE.txt
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (https://cakefoundation.org)
 * @link      https://cakephp.org CakePHP(tm) Project
 * @since     0.2.9
 * @license   https://opensource.org/licenses/mit-license.php MIT License
 */
namespace App\Controller;

use App\Util\Assets;
use App\Util\SetupCase;
use Cake\Core\Configure;
use Cake\Event\EventInterface;
use Cake\Http\Exception\ForbiddenException;
use Cake\Http\Exception\NotFoundException;
use Cake\Http\Response;
use Cake\Routing\Router;
use Cake\View\Exception\MissingTemplateException;
use ReflectionMethod;

/**
 * Static content controller
 *
 * This controller will render views from templates/Pages/
 *
 * @link https://book.cakephp.org/4/en/controllers/pages-controller.html
 */
class CodeBlocksController extends AppController
{

    public function beforeFilter(EventInterface $event)
    {
        $this->set('webroot', Router::url('/'));
        $this->viewBuilder()->setLayout('code_blocks');
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function dashboard() {

    }

    public function index() {
        //Intro page
    }

    public function home() {

    }



    public function responsiveTable() {
        $this->set('menuActive', 'Blokcs');



        $this->set('menuForceActive', 'Blocks');

        $this->set('codeBlocks_title', 'Responsive Table');
        $this->set('codeBlocks_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/CodeBlocks/responsive_table.php'
        ]);

    }



    public function uploadFile() {

        if (!empty($this->request->getData())) {
            $attachment = $this->request->getData('file');
            $filename = $attachment->getClientFilename();
            $typeOfUpload = $attachment->getClientMediaType();
            $size = $attachment->getSize();
            $uploadedFile = $attachment->getStream()->getMetadata('uri');
            $error = $attachment->getError();

            $csvFile = $uploadedFile;

            $filename = APP.'Files'.DS.'uploadProducts_'.date('YmdHis').'.csv';

            file_put_contents($filename,
                file_get_contents($csvFile)
            );

        }

        // IGNORE
        $this->set('codeBlocks_title', 'Upload A File');
        $this->set('codeBlocks_subTitle', 'Auto adjust the table on mobile devices or when screen is thin to show in a nice format');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/upload_file.php'
        ]);
        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
        ]);
        // IGNORE-END


    }



    function readMore() {


        // IGNORE
        $this->set('codeBlocks_title', 'Read More Expanded Text');
        $this->set('codeBlocks_subTitle', 'Long text is faded away - Click link to expanded and show all faded text');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/read_more.php'
        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
//        ]);
        // IGNORE-END
    }



    function sticky() {


        // IGNORE
        $this->set('codeBlocks_title', 'Sticky');
        $this->set('codeBlocks_subTitle', 'Keep a div floating as the window scrolls down');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/sticky.php'
        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
//        ]);
        // IGNORE-END
    }

    function vueJs(){
        $id = 100;
        $this->set(compact('id'));
        $token = $this->request->getAttribute('csrfToken');
        $this->set('csrf', $token);

        $this->set('codeBlocks_title', 'VueJs');
        $this->set('codeBlocks_subTitle', 'VueJs Features and Instructions');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/CodeBlocks/vue_js.php'
        ]);

        $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'vueUpdate')
        ]);


    }

    function vueIndex(){

        $token = $this->request->getAttribute('csrfToken');
        $this->set('csrf', $token);
        $objData=file_get_contents('php://input');
        if(empty($objData)){
            //$objData = '{"name":"newClient","province":"QC","country":"CA"}';
        }

        $data = json_decode($objData, true);
        $id = $data['id'];
        $id++;

        $response = ['STATUS'=>200, 'id'=> $id, 'message' => 'response results success'];


        $this->jsonHeaders(json_encode($response));
        exit;
    }//vueIndex

    function vueUpdate(){
        $token = $this->request->getAttribute('csrfToken');
        $this->set('csrf', $token);
        $objData=file_get_contents('php://input');
        if(empty($objData)){
            $objData = '{"id":100}';
        }
        $data = json_decode($objData, true);



        $id = $data['id'];
        $id++;
        dd($id);

        $response = ['STATUS'=> 200, 'id'=> $id, 'message' => 'response results updated'];


        $this->jsonHeaders(json_encode($response));
        exit;
    }//vueIndex

    function hideAndShowDesktopAndMobile(){

        $this->set('codeBlocks_title', 'Hide And Show Desktop And Mobile');
        $this->set('codeBlocks_subTitle', 'Controlling Visibility on Desktop and Mobile Using CSS');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/CodeBlocks/hide_and_show_desktop_and_mobile.php'
        ]);
    }






    function floatingSubmitBtn() {


        // IGNORE
        $this->set('codeBlocks_title', 'Floating Submit Button');
        $this->set('codeBlocks_subTitle', 'When you scroll away from the submit button it will float on the page');
        $this->set('codeBlocks_renderFiles', [
            'Template' => APP . '../templates/CodeBlocks/floating_submit_btn.php'
        ]);
//        $this->set('codeBlocks_renderVar', [
//            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'uploadFile')
//        ]);
        // IGNORE-END
    }

    function lazyLoadingImages(){
        $this->set('codeBlocks_title', 'Lazy Loading Images');
        $this->set('codeBlocks_subTitle', 'Lazy load images so you do not overload the server with too many image requests');
        $this->set('codeBlocks_renderFiles', [
            'View' => APP . '../templates/CodeBlocks/lazy_loading_images.php'
        ]);
       /* $this->set('codeBlocks_renderVar', [
            'Controller Action' => SetupCase::extractFunction(\App\Controller\CodeBlocksController::class, 'lazyLoadingImages')
        ]);*/

    }

    public function invoice($id, $encrypted_order_id) {


        if ( Assets::doesEncryptionUrlMatch($id, $encrypted_order_id) ) {

            $row = $this->CodeBlocks->get($id);

            //dd($userInfo);
            $this->set(compact('row', ));
        } else {
            die('ERROR: invoice cannot be displayed');
        }
    }




}
